## <%= capitalCamelizedModuleName %> [/<%= pluralizedModuleName %>]
### Create a new <%= entityName %> [POST]

+ Request (application/vnd.api+json)
  + Headers

            Authorization: Bearer e9629c2a-6763-45f4-9d3a-1b2c7822febe
  + Attributes (object, required)
      + data (<%= capitalCamelizedModuleName %>Creation, fixed-type, required)


+ Response 200 (application/vnd.api+json)
  + Attributes (object)
      + data (<%= capitalCamelizedModuleName %>, fixed-type, required) - created object

<!-- include(../../utils/401-response.apib) -->
<!-- include(../../utils/403-response.apib) -->
<!-- include(../../utils/422-response.apib) -->

## <%= capitalCamelizedModuleName %> [/<%= pluralizedModuleName %>?{ids}]
### Retrieve a set of <%= pluralizedModuleName %> [GET]

+ Parameters
  + ids (optional, array, `id[]=1&id[]=2`) ... <%= capitalCamelizedModuleName %> uniq IDs array

+ Request ()
  + Headers

            Authorization: Bearer e9629c2a-6763-45f4-9d3a-1b2c7822febe

+ Response 200 (application/vnd.api+json)
  + Attributes (object)
      + data (array[<%= capitalCamelizedModuleName %>], fixed-type, required) - required objects

<!-- include(../../utils/401-response.apib) -->
<!-- include(../../utils/403-response.apib) -->
<!-- include(../../utils/404-array-response.apib) -->

## <%= capitalCamelizedModuleName %> [/<%= pluralizedModuleName %>/{id}]
### Get one <%= entityName %> [GET]

+ Parameters
  + id (required, number, `1`) ... <%= capitalCamelizedModuleName %> uniq ID

+ Request ()
  + Headers

            Authorization: Bearer e9629c2a-6763-45f4-9d3a-1b2c7822febe

+ Response 200 (application/vnd.api+json)
  + Attributes (object)
      + data (<%= capitalCamelizedModuleName %>, fixed-type, required) - required object

<!-- include(../../utils/401-response.apib) -->
<!-- include(../../utils/403-response.apib) -->
<!-- include(../../utils/404-response.apib) -->


### Update <%=/[aeiouAEIOU]/.test(entityName.charAt(0)) ? 'an' : 'a' %> <%= entityName %> [PATCH]

+ Parameters
  + id (required, number, `1`) ... <%= capitalCamelizedModuleName %> uniq ID

+ Request (application/vnd.api+json)
  + Headers

            Authorization: Bearer e9629c2a-6763-45f4-9d3a-1b2c7822febe
  + Attributes (object)
      + data (<%= capitalCamelizedModuleName %>Update, fixed-type, required)


+ Response 200 (application/vnd.api+json)
  + Attributes (object)
      + data (<%= capitalCamelizedModuleName %>, fixed-type, required) - full serialization of updated

<!-- include(../../utils/401-response.apib) -->
<!-- include(../../utils/403-response.apib) -->
<!-- include(../../utils/404-response.apib) -->
<!-- include(../../utils/422-response.apib) -->


### Delete specified <%= entityName %>  [DELETE]
+ Parameters
    + id (required, number, `1`) ... <%= capitalCamelizedModuleName %> uniq ID

+ Request (application/vnd.api+json)
  + Headers

            Authorization: Bearer e9629c2a-6763-45f4-9d3a-1b2c7822febe

  + Attributes (object)
      + data (<%= capitalCamelizedModuleName %>Type, required)


+ Response 204 ()

<!-- include(../../utils/401-response.apib) -->
<!-- include(../../utils/403-response.apib) -->
<!-- include(../../utils/404-response.apib) -->
