+ Response 404 (application/vnd.api+json)
  + Body

            {
                'errors': [
                  {
                    'title': 'Not found',
                    'detail': 'Resource has not been found on our system'
                  }
                ]
            }
