+ Response 404 (application/vnd.api+json)
  + Body

            {
                'errors': [
                  {
                    'title': 'Not found',
                    'detail': 'One or more of the requested objects has not been found'
                  }
                ]
            }
