+ Response 409 (application/vnd.api+json)
  + Body

            {
                'errors': [
                  {
                    'title': 'Conflict',
                    'detail': 'Resource does not permit this request'
                  }
                ]
            }
