## <%= pluralCapilaCamelModuleName %>  [/<%= pluralizedTargetName %>/{id}/relationships/<%= pluralizedName %>]
### All <%= pluralCapilaCamelModuleName %> [GET]
+ Parameters
    + id (required, number, `1`) ... <%= capitalizedCamelizedTarget %> uniq ID

+ Request ()
  + Headers

            Authorization: Bearer e9629c2a-6763-45f4-9d3a-1b2c7822febe

+ Response 200 (application/vnd.api+json)
  + Attributes (object)
      + data (array[<%= capitalCamelizedModelType %>], fixed-type, required) - full serialization of the related objects

<!-- include(../../../utils/403-response.apib) -->
<!-- include(../../../utils/404-response.apib) -->

### Add <%= pluralCapilaCamelModuleName %> [POST]
+ Parameters
    + id (required, number, `1`) ... <%= capitalizedCamelizedTarget %> uniq ID

+ Request (application/vnd.api+json)
  + Headers

            Authorization: Bearer e9629c2a-6763-45f4-9d3a-1b2c7822febe
  + Attributes (object)
      + data (array[<%= capitalCamelizedModelType %>Type]) - related objects serialized


+ Response 204 ()

<!-- include(../../../utils/403-response.apib) -->
<!-- include(../../../utils/404-response.apib) -->
<!-- include(../../../utils/422-response.apib) -->

### Remove <%= pluralCapilaCamelModuleName %> [DELETE]
+ Parameters
    + id (required, number, `1`) ... <%= capitalizedCamelizedTarget %> uniq ID

+ Request (application/vnd.api+json)
  + Headers

            Authorization: Bearer e9629c2a-6763-45f4-9d3a-1b2c7822febe
  + Attributes (object)
      + data (array[<%= capitalCamelizedModelType %>Type]) - related objects serialized


+ Response 204 ()

<!-- include(../../../utils/403-response.apib) -->
<!-- include(../../../utils/404-array-response.apib) -->
<!-- include(../../../utils/422-response.apib) -->

### Replace ALL <%= pluralCapilaCamelModuleName %> [PATCH]
**NOTE** The following payload will clear the relationship:

```javascript
{
    data: []
}
```

+ Parameters
    + id (required, number, `1`) ... <%= capitalizedCamelizedTarget %> uniq ID

+ Request (application/vnd.api+json)
  + Headers

            Authorization: Bearer e9629c2a-6763-45f4-9d3a-1b2c7822febe
  + Attributes (object)
      + data (array[<%= capitalCamelizedModelType %>Type]) - related objects serialized


+ Response 204 ()

<!-- include(../../../utils/403-response.apib) -->
<!-- include(../../../utils/404-response.apib) -->
<!-- include(../../../utils/422-response.apib) -->
