## <%= capitalCamelizedModuleName %>Base (object)
+ type (enum[string], required)
    + Members
        + `<%= pluralizedModuleName %>`
+ attributes (<%= capitalCamelizedModuleName %>Attributes, required)


## <%= capitalCamelizedModuleName %>Creation (object)
+ Include (<%= capitalCamelizedModuleName %>Base)
+ relationships (<%= capitalCamelizedModuleName %>Relationships, required)


## <%= capitalCamelizedModuleName %>Update (object)
+ id: 1 (number, required) - unique ID
+ Include (<%= capitalCamelizedModuleName %>Base)


## <%= capitalCamelizedModuleName %> (object)
+ id: 1 (number, required) - unique ID
+ Include (<%= capitalCamelizedModuleName %>Creation)


## <%= capitalCamelizedModuleName %>Attributes (object)
+ name (string) - attribute example

## <%= capitalCamelizedModuleName %>Relationships (object)



## <%= capitalCamelizedModuleName %>Type (object)
+ id: 1 (number, required) - unique ID
+ type (enum[string], required)
    + Members
        + `<%= pluralizedModuleName %>`