## <%= capitalCamelizedModuleName %>BaseType (object)
+ type (enum, required)
    + Members
        + `<%= pluralizedModuleName %>` (string)

## <%= capitalCamelizedModuleName %>Base (object)
+ Include <%= capitalCamelizedModuleName %>BaseType
+ attributes (object, required)
    + Include (<%= capitalCamelizedModuleName %>RequiredAttributes)
    + Include (<%= capitalCamelizedModuleName %>Attributes)
    + Include (<%= capitalCamelizedModuleName %>ReadOnlyAttributes)

## <%= capitalCamelizedModuleName %>RequiredRelationships (object)

## <%= capitalCamelizedModuleName %>OptionalRelationships (object)

## <%= capitalCamelizedModuleName %>RequiredAttributes (object)

## <%= capitalCamelizedModuleName %>ReadOnlyAttributes (object)

## <%= capitalCamelizedModuleName %>Attributes (object)
+ name (string) - attribute example


## <%= capitalCamelizedModuleName %>Creation (object)
+ Include <%= capitalCamelizedModuleName %>BaseType
+ attributes (<%= capitalCamelizedModuleName %>RequiredAttributes)
+ relationships (<%= capitalCamelizedModuleName %>RequiredRelationships)


## <%= capitalCamelizedModuleName %>Update (object)
+ id: 1 (number, required) - unique ID
+ Include <%= capitalCamelizedModuleName %>BaseType
+ attributes (object)
    + Include (<%= capitalCamelizedModuleName %>RequiredAttributes)
    + Include (<%= capitalCamelizedModuleName %>Attributes)


## <%= capitalCamelizedModuleName %> (object)
+ id: 1 (number, required) - unique ID
+ Include (<%= capitalCamelizedModuleName %>Base)
+ relationships (<%= capitalCamelizedModuleName %>Relationships)


## <%= capitalCamelizedModuleName %>Relationships (object)
+ Include (<%= capitalCamelizedModuleName %>RequiredRelationships)
+ Include (<%= capitalCamelizedModuleName %>OptionalRelationships)



## <%= capitalCamelizedModuleName %>Type (object)
+ id: 1 (number, required) - unique ID
+ Include <%= capitalCamelizedModuleName %>BaseType