## <%= capitalCamelizedModuleName %>
+ id: 1 (number, required) - unique ID
+ type: <%= camelizedModuleName %> (string, required)
+ attributes (<%= capitalCamelizedModuleName %>Attributes, required)
+ relationships (<%= capitalCamelizedModuleName %>Relationships, required)

## <%= capitalCamelizedModuleName %>Attributes (object)
+ name (string) - attribute example

## <%= capitalCamelizedModuleName %>Relationships (object)



## <%= capitalCamelizedModuleName %>Type (object)
+ id: 1 (number, required) - unique ID
+ type: <%= camelizedModuleName %> (string, required)